In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.DataFrame({
    "customer_id": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "customer_name": [
        "John Smith","Emma Johnson","Michael Brown","Sophia Davis","James Wilson",
        "Olivia Miller","William Moore","Ava Taylor","Benjamin Anderson","Isabella Thomas",
        "Lucas Jackson","Mia White","Henry Harris","Charlotte Martin","Daniel Thompson"
    ],
    "city": [
        "Dallas","Austin","Houston","Dallas","Chicago",
        "Austin","Seattle","Dallas","Miami","Houston",
        "Phoenix","Dallas","Austin","Chicago","Seattle"
    ],
    "age":[32,28,41,35,29,38,45,26,31,27,36,24,42,33,39]
})

customers

    customer_id      customer_name     city  age
0             1         John Smith   Dallas   32
1             2       Emma Johnson   Austin   28
2             3      Michael Brown  Houston   41
3             4       Sophia Davis   Dallas   35
4             5       James Wilson  Chicago   29
5             6      Olivia Miller   Austin   38
6             7      William Moore  Seattle   45
7             8         Ava Taylor   Dallas   26
8             9  Benjamin Anderson    Miami   31
9            10    Isabella Thomas  Houston   27
10           11      Lucas Jackson  Phoenix   36
11           12          Mia White   Dallas   24
12           13       Henry Harris   Austin   42
13           14   Charlotte Martin  Chicago   33
14           15    Daniel Thompson  Seattle   39

In [3]:
products = pd.DataFrame({
    "product_id":[101,102,103,104,105,106,107,108,109,110,
                  111,112,113,114,115,116,117,118,119,120],
    "product_name":[
        "Laptop","Smartphone","Tablet","Headphones","Smart Watch",
        "Refrigerator","Microwave","Washing Machine","Air Conditioner","Vacuum Cleaner",
        "Office Chair","Dining Table","Sofa","Bookshelf","Bed Frame",
        "Running Shoes","Football","Tennis Racket","Gym Bag","Yoga Mat"
    ],
    "category":[
        "Electronics","Electronics","Electronics","Electronics","Electronics",
        "Home Appliances","Home Appliances","Home Appliances","Home Appliances","Home Appliances",
        "Furniture","Furniture","Furniture","Furniture","Furniture",
        "Sports","Sports","Sports","Sports","Sports"
    ],
    "price":[1200,800,500,150,250,1400,300,900,1100,220,
             180,650,950,275,750,120,45,180,65,35],
    "stock":[15,25,18,40,22,10,12,8,7,14,
             30,9,6,16,5,35,50,20,28,45]
})

products

    product_id     product_name         category  price  stock
0          101           Laptop      Electronics   1200     15
1          102       Smartphone      Electronics    800     25
2          103           Tablet      Electronics    500     18
3          104       Headphones      Electronics    150     40
4          105      Smart Watch      Electronics    250     22
5          106     Refrigerator  Home Appliances   1400     10
6          107        Microwave  Home Appliances    300     12
7          108  Washing Machine  Home Appliances    900      8
8          109  Air Conditioner  Home Appliances   1100      7
9          110   Vacuum Cleaner  Home Appliances    220     14
10         111     Office Chair        Furniture    180     30
11         112     Dining Table        Furniture    650      9
12         113             Sofa        Furniture    950      6
13         114        Bookshelf        Furniture    275     16
14         115        Bed Frame        Furniture    750      5
15         116    Running Shoes           Sports    120     35
16         117         Football           Sports     45     50
17         118    Tennis Racket           Sports    180     20
18         119          Gym Bag           Sports     65     28
19         120         Yoga Mat           Sports     35     45

In [4]:
orders = pd.DataFrame({
    "order_id":[
        1,2,3,4,5,6,7,8,9,10,
        11,12,13,14,15,16,17,18,19,20,
        21,22,23,24,25,26,27,28,29,30,
        31,32,33,34,35,36,37,38,39,40
    ],
    "customer_id":[
        1,2,3,4,5,6,7,8,9,10,
        11,12,13,14,15,1,2,3,4,5,
        6,7,8,9,10,11,12,13,14,15,
        1,2,3,4,5,6,7,8,9,10
    ],
    "product_id":[
        101,102,103,104,105,106,107,108,109,110,
        111,112,113,114,115,116,117,118,119,120,
        101,102,103,104,105,106,107,108,109,110,
        111,112,113,114,115,116,117,118,119,120
    ],
    "quantity":[
        1,2,1,3,2,1,2,1,1,2,
        3,1,1,2,1,2,4,1,2,3,
        1,1,2,2,1,1,1,1,1,2,
        2,1,1,1,1,3,5,2,1,4
    ],
    "total_amount":[
        1200,1600,500,450,500,1400,600,900,1100,440,
        540,650,950,550,750,240,180,180,130,105,
        1200,800,1000,300,250,1400,300,900,1100,440,
        360,650,950,275,750,360,225,360,65,140
    ],
    "order_date":[
        "2024-01-05","2024-01-06","2024-01-07","2024-01-08","2024-01-09",
        "2024-01-10","2024-01-11","2024-01-12","2024-01-13","2024-01-14",
        "2024-01-15","2024-01-16","2024-01-17","2024-01-18","2024-01-19",
        "2024-01-20","2024-01-21","2024-01-22","2024-01-23","2024-01-24",
        "2024-02-01","2024-02-02","2024-02-03","2024-02-04","2024-02-05",
        "2024-02-06","2024-02-07","2024-02-08","2024-02-09","2024-02-10",
        "2024-02-11","2024-02-12","2024-02-13","2024-02-14","2024-02-15",
        "2024-02-16","2024-02-17","2024-02-18","2024-02-19","2024-02-20"
    ]
})

# Convert order_date to datetime
orders["order_date"] = pd.to_datetime(orders["order_date"])

# Display the DataFrame
orders

    order_id  customer_id  product_id  quantity  total_amount order_date
0          1            1         101         1          1200 2024-01-05
1          2            2         102         2          1600 2024-01-06
2          3            3         103         1           500 2024-01-07
3          4            4         104         3           450 2024-01-08
4          5            5         105         2           500 2024-01-09
5          6            6         106         1          1400 2024-01-10
6          7            7         107         2           600 2024-01-11
7          8            8         108         1           900 2024-01-12
8          9            9         109         1          1100 2024-01-13
9         10           10         110         2           440 2024-01-14
10        11           11         111         3           540 2024-01-15
11        12           12         112         1           650 2024-01-16
12        13           13         113         1           950 2024-01-17
13        14           14         114         2           550 2024-01-18
14        15           15         115         1           750 2024-01-19
15        16            1         116         2           240 2024-01-20
16        17            2         117         4           180 2024-01-21
17        18            3         118         1           180 2024-01-22
18        19            4         119         2           130 2024-01-23
19        20            5         120         3           105 2024-01-24
20        21            6         101         1          1200 2024-02-01
21        22            7         102         1           800 2024-02-02
22        23            8         103         2          1000 2024-02-03
23        24            9         104         2           300 2024-02-04
24        25           10         105         1           250 2024-02-05
25        26           11         106         1          1400 2024-02-06
26        27           12         107         1           300 2024-02-07
27        28           13         108         1           900 2024-02-08
28        29           14         109         1          1100 2024-02-09
29        30           15         110         2           440 2024-02-10
30        31            1         111         2           360 2024-02-11
31        32            2         112         1           650 2024-02-12
32        33            3         113         1           950 2024-02-13
33        34            4         114         1           275 2024-02-14
34        35            5         115         1           750 2024-02-15
35        36            6         116         3           360 2024-02-16
36        37            7         117         5           225 2024-02-17
37        38            8         118         2           360 2024-02-18
38        39            9         119         1            65 2024-02-19
39        40           10         120         4           140 2024-02-20

In [5]:
# 1

In [6]:
customers

    customer_id      customer_name     city  age
0             1         John Smith   Dallas   32
1             2       Emma Johnson   Austin   28
2             3      Michael Brown  Houston   41
3             4       Sophia Davis   Dallas   35
4             5       James Wilson  Chicago   29
5             6      Olivia Miller   Austin   38
6             7      William Moore  Seattle   45
7             8         Ava Taylor   Dallas   26
8             9  Benjamin Anderson    Miami   31
9            10    Isabella Thomas  Houston   27
10           11      Lucas Jackson  Phoenix   36
11           12          Mia White   Dallas   24
12           13       Henry Harris   Austin   42
13           14   Charlotte Martin  Chicago   33
14           15    Daniel Thompson  Seattle   39

In [7]:
# 2
products

    product_id     product_name         category  price  stock
0          101           Laptop      Electronics   1200     15
1          102       Smartphone      Electronics    800     25
2          103           Tablet      Electronics    500     18
3          104       Headphones      Electronics    150     40
4          105      Smart Watch      Electronics    250     22
5          106     Refrigerator  Home Appliances   1400     10
6          107        Microwave  Home Appliances    300     12
7          108  Washing Machine  Home Appliances    900      8
8          109  Air Conditioner  Home Appliances   1100      7
9          110   Vacuum Cleaner  Home Appliances    220     14
10         111     Office Chair        Furniture    180     30
11         112     Dining Table        Furniture    650      9
12         113             Sofa        Furniture    950      6
13         114        Bookshelf        Furniture    275     16
14         115        Bed Frame        Furniture    750      5
15         116    Running Shoes           Sports    120     35
16         117         Football           Sports     45     50
17         118    Tennis Racket           Sports    180     20
18         119          Gym Bag           Sports     65     28
19         120         Yoga Mat           Sports     35     45

In [8]:
# 3
orders

    order_id  customer_id  product_id  quantity  total_amount order_date
0          1            1         101         1          1200 2024-01-05
1          2            2         102         2          1600 2024-01-06
2          3            3         103         1           500 2024-01-07
3          4            4         104         3           450 2024-01-08
4          5            5         105         2           500 2024-01-09
5          6            6         106         1          1400 2024-01-10
6          7            7         107         2           600 2024-01-11
7          8            8         108         1           900 2024-01-12
8          9            9         109         1          1100 2024-01-13
9         10           10         110         2           440 2024-01-14
10        11           11         111         3           540 2024-01-15
11        12           12         112         1           650 2024-01-16
12        13           13         113         1           950 2024-01-17
13        14           14         114         2           550 2024-01-18
14        15           15         115         1           750 2024-01-19
15        16            1         116         2           240 2024-01-20
16        17            2         117         4           180 2024-01-21
17        18            3         118         1           180 2024-01-22
18        19            4         119         2           130 2024-01-23
19        20            5         120         3           105 2024-01-24
20        21            6         101         1          1200 2024-02-01
21        22            7         102         1           800 2024-02-02
22        23            8         103         2          1000 2024-02-03
23        24            9         104         2           300 2024-02-04
24        25           10         105         1           250 2024-02-05
25        26           11         106         1          1400 2024-02-06
26        27           12         107         1           300 2024-02-07
27        28           13         108         1           900 2024-02-08
28        29           14         109         1          1100 2024-02-09
29        30           15         110         2           440 2024-02-10
30        31            1         111         2           360 2024-02-11
31        32            2         112         1           650 2024-02-12
32        33            3         113         1           950 2024-02-13
33        34            4         114         1           275 2024-02-14
34        35            5         115         1           750 2024-02-15
35        36            6         116         3           360 2024-02-16
36        37            7         117         5           225 2024-02-17
37        38            8         118         2           360 2024-02-18
38        39            9         119         1            65 2024-02-19
39        40           10         120         4           140 2024-02-20

In [9]:
# 4
customers[['customer_name', 'city']]

        customer_name     city
0          John Smith   Dallas
1        Emma Johnson   Austin
2       Michael Brown  Houston
3        Sophia Davis   Dallas
4        James Wilson  Chicago
5       Olivia Miller   Austin
6       William Moore  Seattle
7          Ava Taylor   Dallas
8   Benjamin Anderson    Miami
9     Isabella Thomas  Houston
10      Lucas Jackson  Phoenix
11          Mia White   Dallas
12       Henry Harris   Austin
13   Charlotte Martin  Chicago
14    Daniel Thompson  Seattle

In [10]:
# 5
products[['product_name', 'price']]

       product_name  price
0            Laptop   1200
1        Smartphone    800
2            Tablet    500
3        Headphones    150
4       Smart Watch    250
5      Refrigerator   1400
6         Microwave    300
7   Washing Machine    900
8   Air Conditioner   1100
9    Vacuum Cleaner    220
10     Office Chair    180
11     Dining Table    650
12             Sofa    950
13        Bookshelf    275
14        Bed Frame    750
15    Running Shoes    120
16         Football     45
17    Tennis Racket    180
18          Gym Bag     65
19         Yoga Mat     35

In [11]:
# 6
customers['city'].drop_duplicates()

0      Dallas
1      Austin
2     Houston
4     Chicago
6     Seattle
8       Miami
10    Phoenix
Name: city, dtype: object

In [12]:
# 7
products['category'].drop_duplicates()

0         Electronics
5     Home Appliances
10          Furniture
15             Sports
Name: category, dtype: object

In [13]:
# 8
customers[customers['city'] == 'Dallas']

    customer_id customer_name    city  age
0             1    John Smith  Dallas   32
3             4  Sophia Davis  Dallas   35
7             8    Ava Taylor  Dallas   26
11           12     Mia White  Dallas   24

In [14]:
# 9
customers[customers['age'] > 30]

    customer_id      customer_name     city  age
0             1         John Smith   Dallas   32
2             3      Michael Brown  Houston   41
3             4       Sophia Davis   Dallas   35
5             6      Olivia Miller   Austin   38
6             7      William Moore  Seattle   45
8             9  Benjamin Anderson    Miami   31
10           11      Lucas Jackson  Phoenix   36
12           13       Henry Harris   Austin   42
13           14   Charlotte Martin  Chicago   33
14           15    Daniel Thompson  Seattle   39

In [15]:
# 10
products[products['price'] > 500]

    product_id     product_name         category  price  stock
0          101           Laptop      Electronics   1200     15
1          102       Smartphone      Electronics    800     25
5          106     Refrigerator  Home Appliances   1400     10
7          108  Washing Machine  Home Appliances    900      8
8          109  Air Conditioner  Home Appliances   1100      7
11         112     Dining Table        Furniture    650      9
12         113             Sofa        Furniture    950      6
14         115        Bed Frame        Furniture    750      5

In [16]:
# 11
products[products['stock'] < 20]

    product_id     product_name         category  price  stock
0          101           Laptop      Electronics   1200     15
2          103           Tablet      Electronics    500     18
5          106     Refrigerator  Home Appliances   1400     10
6          107        Microwave  Home Appliances    300     12
7          108  Washing Machine  Home Appliances    900      8
8          109  Air Conditioner  Home Appliances   1100      7
9          110   Vacuum Cleaner  Home Appliances    220     14
11         112     Dining Table        Furniture    650      9
12         113             Sofa        Furniture    950      6
13         114        Bookshelf        Furniture    275     16
14         115        Bed Frame        Furniture    750      5

In [17]:
# 12
orders[orders['total_amount'] > 1000]

    order_id  customer_id  product_id  quantity  total_amount order_date
0          1            1         101         1          1200 2024-01-05
1          2            2         102         2          1600 2024-01-06
5          6            6         106         1          1400 2024-01-10
8          9            9         109         1          1100 2024-01-13
20        21            6         101         1          1200 2024-02-01
25        26           11         106         1          1400 2024-02-06
28        29           14         109         1          1100 2024-02-09

In [18]:
# 13
customers[(customers['city'] == 'Dallas') & (customers['age'] > 30)]

   customer_id customer_name    city  age
0            1    John Smith  Dallas   32
3            4  Sophia Davis  Dallas   35

In [19]:
# 14
customers[(customers['city'] == 'Dallas') | (customers['city'] == 'Austin')]

    customer_id  customer_name    city  age
0             1     John Smith  Dallas   32
1             2   Emma Johnson  Austin   28
3             4   Sophia Davis  Dallas   35
5             6  Olivia Miller  Austin   38
7             8     Ava Taylor  Dallas   26
11           12      Mia White  Dallas   24
12           13   Henry Harris  Austin   42

In [20]:
# 15
products[products['category'] == 'Electronics']

   product_id product_name     category  price  stock
0         101       Laptop  Electronics   1200     15
1         102   Smartphone  Electronics    800     25
2         103       Tablet  Electronics    500     18
3         104   Headphones  Electronics    150     40
4         105  Smart Watch  Electronics    250     22

In [21]:
# 16
orders[(orders['order_date'] >= '2024-01-10') &
       (orders['order_date'] <= '2024-02-10')]

    order_id  customer_id  product_id  quantity  total_amount order_date
5          6            6         106         1          1400 2024-01-10
6          7            7         107         2           600 2024-01-11
7          8            8         108         1           900 2024-01-12
8          9            9         109         1          1100 2024-01-13
9         10           10         110         2           440 2024-01-14
10        11           11         111         3           540 2024-01-15
11        12           12         112         1           650 2024-01-16
12        13           13         113         1           950 2024-01-17
13        14           14         114         2           550 2024-01-18
14        15           15         115         1           750 2024-01-19
15        16            1         116         2           240 2024-01-20
16        17            2         117         4           180 2024-01-21
17        18            3         118         1           180 2024-01-22
18        19            4         119         2           130 2024-01-23
19        20            5         120         3           105 2024-01-24
20        21            6         101         1          1200 2024-02-01
21        22            7         102         1           800 2024-02-02
22        23            8         103         2          1000 2024-02-03
23        24            9         104         2           300 2024-02-04
24        25           10         105         1           250 2024-02-05
25        26           11         106         1          1400 2024-02-06
26        27           12         107         1           300 2024-02-07
27        28           13         108         1           900 2024-02-08
28        29           14         109         1          1100 2024-02-09
29        30           15         110         2           440 2024-02-10

In [22]:
# 17
customers[customers['customer_name'].str.startswith('J')]

   customer_id customer_name     city  age
0            1    John Smith   Dallas   32
4            5  James Wilson  Chicago   29

In [23]:
# 18
customers.sort_values(by='age')

# 19
products.sort_values(by='price')

# 20
orders.sort_values(by='total_amount')

# 21
products.sort_values(by='price', ascending=False).head(5)

# 22
orders.sort_values(by='total_amount', ascending=False).head(5)

    order_id  customer_id  product_id  quantity  total_amount order_date
1          2            2         102         2          1600 2024-01-06
5          6            6         106         1          1400 2024-01-10
25        26           11         106         1          1400 2024-02-06
0          1            1         101         1          1200 2024-01-05
20        21            6         101         1          1200 2024-02-01

In [77]:
# 23
customers['customer_id'].count()

np.int64(15)

In [25]:
# 24
products['product_id'].count()

np.int64(20)

In [26]:
# 25
orders['order_id'].count()

np.int64(40)

In [27]:
# 26
orders['total_amount'].sum()

np.int64(24790)

In [28]:
# 27
orders['total_amount'].mean()

np.float64(619.75)

In [29]:
# 28
orders['total_amount'].max()

1600

In [30]:
# 29
orders['total_amount'].min()

65

In [31]:
# 30
products['price'].mean()

np.float64(503.5)

In [32]:
# 31
customers.groupby('city')['customer_id'].count().reset_index(name='customer_count')

      city  customer_count
0   Austin               3
1  Chicago               2
2   Dallas               4
3  Houston               2
4    Miami               1
5  Phoenix               1
6  Seattle               2

In [33]:
# 32
products.groupby('category')['product_id'].count().reset_index(name='product_count')

          category  product_count
0      Electronics              5
1        Furniture              5
2  Home Appliances              5
3           Sports              5

In [34]:
# 33
orders.merge(customers, on='customer_id') \
      .groupby('customer_name')['total_amount'] \
      .sum() \
      .reset_index(name='total_sales')

        customer_name  total_sales
0          Ava Taylor         2260
1   Benjamin Anderson         1465
2    Charlotte Martin         1650
3     Daniel Thompson         1190
4        Emma Johnson         2430
5        Henry Harris         1850
6     Isabella Thomas          830
7        James Wilson         1355
8          John Smith         1800
9       Lucas Jackson         1940
10          Mia White          950
11      Michael Brown         1630
12      Olivia Miller         2960
13       Sophia Davis          855
14      William Moore         1625

In [35]:
# 34
orders.merge(products, on='product_id') \
      .groupby('product_name')['total_amount'] \
      .sum() \
      .reset_index(name='total_sales')

       product_name  total_sales
0   Air Conditioner         2200
1         Bed Frame         1500
2         Bookshelf          825
3      Dining Table         1300
4          Football          405
5           Gym Bag          195
6        Headphones          750
7            Laptop         2400
8         Microwave          900
9      Office Chair          900
10     Refrigerator         2800
11    Running Shoes          600
12      Smart Watch          750
13       Smartphone         2400
14             Sofa         1900
15           Tablet         1500
16    Tennis Racket          540
17   Vacuum Cleaner          880
18  Washing Machine         1800
19         Yoga Mat          245

In [36]:
# 35
orders.merge(products, on='product_id') \
      .groupby('category')['total_amount'] \
      .sum() \
      .reset_index(name='total_sales')

          category  total_sales
0      Electronics         7800
1        Furniture         6425
2  Home Appliances         8580
3           Sports         1985

In [37]:
# 36
orders.merge(customers, on='customer_id') \
    .groupby('city')['total_amount'] \
    .mean() \
    .reset_index(name='average_order_value')

      city  average_order_value
0   Austin           905.000000
1  Chicago           601.000000
2   Dallas           533.181818
3  Houston           410.000000
4    Miami           488.333333
5  Phoenix           970.000000
6  Seattle           563.000000

In [38]:
# 37
orders.merge(customers, on='customer_id') \
      .groupby('city')['total_amount'] \
      .max() \
      .reset_index(name='maximum_order_amount')

      city  maximum_order_amount
0   Austin                  1600
1  Chicago                  1100
2   Dallas                  1200
3  Houston                   950
4    Miami                  1100
5  Phoenix                  1400
6  Seattle                   800

In [39]:
# 38
orders.merge(products, on='product_id') \
      .groupby('product_name')['quantity'] \
      .sum() \
      .reset_index(name='total_quantity_sold')

       product_name  total_quantity_sold
0   Air Conditioner                    2
1         Bed Frame                    2
2         Bookshelf                    3
3      Dining Table                    2
4          Football                    9
5           Gym Bag                    3
6        Headphones                    5
7            Laptop                    2
8         Microwave                    3
9      Office Chair                    5
10     Refrigerator                    2
11    Running Shoes                    5
12      Smart Watch                    3
13       Smartphone                    3
14             Sofa                    2
15           Tablet                    3
16    Tennis Racket                    3
17   Vacuum Cleaner                    4
18  Washing Machine                    2
19         Yoga Mat                    7

In [40]:
# 39
orders.merge(customers, on='customer_id')[['customer_name', 'total_amount']]

        customer_name  total_amount
0          John Smith          1200
1        Emma Johnson          1600
2       Michael Brown           500
3        Sophia Davis           450
4        James Wilson           500
5       Olivia Miller          1400
6       William Moore           600
7          Ava Taylor           900
8   Benjamin Anderson          1100
9     Isabella Thomas           440
10      Lucas Jackson           540
11          Mia White           650
12       Henry Harris           950
13   Charlotte Martin           550
14    Daniel Thompson           750
15         John Smith           240
16       Emma Johnson           180
17      Michael Brown           180
18       Sophia Davis           130
19       James Wilson           105
20      Olivia Miller          1200
21      William Moore           800
22         Ava Taylor          1000
23  Benjamin Anderson           300
24    Isabella Thomas           250
25      Lucas Jackson          1400
26          Mia White           300
27       Henry Harris           900
28   Charlotte Martin          1100
29    Daniel Thompson           440
30         John Smith           360
31       Emma Johnson           650
32      Michael Brown           950
33       Sophia Davis           275
34       James Wilson           750
35      Olivia Miller           360
36      William Moore           225
37         Ava Taylor           360
38  Benjamin Anderson            65
39    Isabella Thomas           140

In [41]:
# 40
orders.merge(customers, on='customer_id') \
      .merge(products, on='product_id')[['customer_name', 'product_name']]

        customer_name     product_name
0          John Smith           Laptop
1        Emma Johnson       Smartphone
2       Michael Brown           Tablet
3        Sophia Davis       Headphones
4        James Wilson      Smart Watch
5       Olivia Miller     Refrigerator
6       William Moore        Microwave
7          Ava Taylor  Washing Machine
8   Benjamin Anderson  Air Conditioner
9     Isabella Thomas   Vacuum Cleaner
10      Lucas Jackson     Office Chair
11          Mia White     Dining Table
12       Henry Harris             Sofa
13   Charlotte Martin        Bookshelf
14    Daniel Thompson        Bed Frame
15         John Smith    Running Shoes
16       Emma Johnson         Football
17      Michael Brown    Tennis Racket
18       Sophia Davis          Gym Bag
19       James Wilson         Yoga Mat
20      Olivia Miller           Laptop
21      William Moore       Smartphone
22         Ava Taylor           Tablet
23  Benjamin Anderson       Headphones
24    Isabella Thomas      Smart Watch
25      Lucas Jackson     Refrigerator
26          Mia White        Microwave
27       Henry Harris  Washing Machine
28   Charlotte Martin  Air Conditioner
29    Daniel Thompson   Vacuum Cleaner
30         John Smith     Office Chair
31       Emma Johnson     Dining Table
32      Michael Brown             Sofa
33       Sophia Davis        Bookshelf
34       James Wilson        Bed Frame
35      Olivia Miller    Running Shoes
36      William Moore         Football
37         Ava Taylor    Tennis Racket
38  Benjamin Anderson          Gym Bag
39    Isabella Thomas         Yoga Mat

In [42]:
# 41
orders.merge(customers, on='customer_id') \
      .merge(products, on='product_id')[['customer_name', 'product_name', 'quantity', 'total_amount']]

        customer_name     product_name  quantity  total_amount
0          John Smith           Laptop         1          1200
1        Emma Johnson       Smartphone         2          1600
2       Michael Brown           Tablet         1           500
3        Sophia Davis       Headphones         3           450
4        James Wilson      Smart Watch         2           500
5       Olivia Miller     Refrigerator         1          1400
6       William Moore        Microwave         2           600
7          Ava Taylor  Washing Machine         1           900
8   Benjamin Anderson  Air Conditioner         1          1100
9     Isabella Thomas   Vacuum Cleaner         2           440
10      Lucas Jackson     Office Chair         3           540
11          Mia White     Dining Table         1           650
12       Henry Harris             Sofa         1           950
13   Charlotte Martin        Bookshelf         2           550
14    Daniel Thompson        Bed Frame         1           750
15         John Smith    Running Shoes         2           240
16       Emma Johnson         Football         4           180
17      Michael Brown    Tennis Racket         1           180
18       Sophia Davis          Gym Bag         2           130
19       James Wilson         Yoga Mat         3           105
20      Olivia Miller           Laptop         1          1200
21      William Moore       Smartphone         1           800
22         Ava Taylor           Tablet         2          1000
23  Benjamin Anderson       Headphones         2           300
24    Isabella Thomas      Smart Watch         1           250
25      Lucas Jackson     Refrigerator         1          1400
26          Mia White        Microwave         1           300
27       Henry Harris  Washing Machine         1           900
28   Charlotte Martin  Air Conditioner         1          1100
29    Daniel Thompson   Vacuum Cleaner         2           440
30         John Smith     Office Chair         2           360
31       Emma Johnson     Dining Table         1           650
32      Michael Brown             Sofa         1           950
33       Sophia Davis        Bookshelf         1           275
34       James Wilson        Bed Frame         1           750
35      Olivia Miller    Running Shoes         3           360
36      William Moore         Football         5           225
37         Ava Taylor    Tennis Racket         2           360
38  Benjamin Anderson          Gym Bag         1            65
39    Isabella Thomas         Yoga Mat         4           140

In [43]:
# 42
orders.merge(customers, on='customer_id') \
      .merge(products, on='product_id')[['customer_name', 'city', 'product_name', 'category', 'total_amount']]

        customer_name     city     product_name         category  total_amount
0          John Smith   Dallas           Laptop      Electronics          1200
1        Emma Johnson   Austin       Smartphone      Electronics          1600
2       Michael Brown  Houston           Tablet      Electronics           500
3        Sophia Davis   Dallas       Headphones      Electronics           450
4        James Wilson  Chicago      Smart Watch      Electronics           500
5       Olivia Miller   Austin     Refrigerator  Home Appliances          1400
6       William Moore  Seattle        Microwave  Home Appliances           600
7          Ava Taylor   Dallas  Washing Machine  Home Appliances           900
8   Benjamin Anderson    Miami  Air Conditioner  Home Appliances          1100
9     Isabella Thomas  Houston   Vacuum Cleaner  Home Appliances           440
10      Lucas Jackson  Phoenix     Office Chair        Furniture           540
11          Mia White   Dallas     Dining Table        Furniture           650
12       Henry Harris   Austin             Sofa        Furniture           950
13   Charlotte Martin  Chicago        Bookshelf        Furniture           550
14    Daniel Thompson  Seattle        Bed Frame        Furniture           750
15         John Smith   Dallas    Running Shoes           Sports           240
16       Emma Johnson   Austin         Football           Sports           180
17      Michael Brown  Houston    Tennis Racket           Sports           180
18       Sophia Davis   Dallas          Gym Bag           Sports           130
19       James Wilson  Chicago         Yoga Mat           Sports           105
20      Olivia Miller   Austin           Laptop      Electronics          1200
21      William Moore  Seattle       Smartphone      Electronics           800
22         Ava Taylor   Dallas           Tablet      Electronics          1000
23  Benjamin Anderson    Miami       Headphones      Electronics           300
24    Isabella Thomas  Houston      Smart Watch      Electronics           250
25      Lucas Jackson  Phoenix     Refrigerator  Home Appliances          1400
26          Mia White   Dallas        Microwave  Home Appliances           300
27       Henry Harris   Austin  Washing Machine  Home Appliances           900
28   Charlotte Martin  Chicago  Air Conditioner  Home Appliances          1100
29    Daniel Thompson  Seattle   Vacuum Cleaner  Home Appliances           440
30         John Smith   Dallas     Office Chair        Furniture           360
31       Emma Johnson   Austin     Dining Table        Furniture           650
32      Michael Brown  Houston             Sofa        Furniture           950
33       Sophia Davis   Dallas        Bookshelf        Furniture           275
34       James Wilson  Chicago        Bed Frame        Furniture           750
35      Olivia Miller   Austin    Running Shoes           Sports           360
36      William Moore  Seattle         Football           Sports           225
37         Ava Taylor   Dallas    Tennis Racket           Sports           360
38  Benjamin Anderson    Miami          Gym Bag           Sports            65
39    Isabella Thomas  Houston         Yoga Mat           Sports           140

In [44]:
# 43
orders.merge(customers, on='customer_id') \
      .merge(products, on='product_id')[
          ['customer_name', 'city', 'product_name', 'category',
           'price', 'quantity', 'total_amount', 'order_date']
      ]

,customer_name,city,product_name,category,price,quantity,total_amount,order_date
0,John Smith,Dallas,Laptop,Electronics,1200,1,1200,2024-01-05
1,Emma Johnson,Austin,Smartphone,Electronics,800,2,1600,2024-01-06
2,Michael Brown,Houston,Tablet,Electronics,500,1,500,2024-01-07
3,Sophia Davis,Dallas,Headphones,Electronics,150,3,450,2024-01-08
4,James Wilson,Chicago,Smart Watch,Electronics,250,2,500,2024-01-09
5,Olivia Miller,Austin,Refrigerator,Home Appliances,1400,1,1400,2024-01-10
6,William Moore,Seattle,Microwave,Home Appliances,300,2,600,2024-01-11
7,Ava Taylor,Dallas,Washing Machine,Home Appliances,900,1,900,2024-01-12
8,Benjamin Anderson,Miami,Air Conditioner,Home Appliances,1100,1,1100,2024-01-13
9,Isabella Thomas,Houston,Vacuum Cleaner,Home Appliances,220,2,440,2024-01-14
10,Lucas Jackson,Phoenix,Office Chair,Furniture,180,3,540,2024-01-15
11,Mia White,Dallas,Dining Table,Furniture,650,1,650,2024-01-16
12,Henry Harris,Austin,Sofa,Furniture,950,1,950,2024-01-17
13,Charlotte Martin,Chicago,Bookshelf,Furniture,275,2,550,2024-01-18
14,Daniel Thompson,Seattle,Bed Frame,Furniture,750,1,750,2024-01-19
15,John Smith,Dallas,Running Shoes,Sports,120,2,240,2024-01-20
16,Emma Johnson,Austin,Football,Sports,45,4,180,2024-01-21
17,Michael Brown,Houston,Tennis Racket,Sports,180,1,180,2024-01-22
18,Sophia Davis,Dallas,Gym Bag,Sports,65,2,130,2024-01-23
19,James Wilson,Chicago,Yoga Mat,Sports,35,3,105,2024-01-24
20,Olivia Miller,Austin,Laptop,Electronics,1200,1,1200,2024-02-01
21,William Moore,Seattle,Smartphone,Electronics,800,1,800,2024-02-02
22,Ava Taylor,Dallas,Tablet,Electronics,500,2,1000,2024-02-03
23,Benjamin Anderson,Miami,Headphones,Electronics,150,2,300,2024-02-04
24,Isabella Thomas,Houston,Smart Watch,Electronics,250,1,250,2024-02-05
25,Lucas Jackson,Phoenix,Refrigerator,Home Appliances,1400,1,1400,2024-02-06
26,Mia White,Dallas,Microwave,Home Appliances,300,1,300,2024-02-07
27,Henry Harris,Austin,Washing Machine,Home Appliances,900,1,900,2024-02-08
28,Charlotte Martin,Chicago,Air Conditioner,Home Appliances,1100,1,1100,2024-02-09
29,Daniel Thompson,Seattle,Vacuum Cleaner,Home Appliances,220,2,440,2024-02-10
30,John Smith,Dallas,Office Chair,Furniture,180,2,360,2024-02-11
31,Emma Johnson,Austin,Dining Table,Furniture,650,1,650,2024-02-12
32,Michael Brown,Houston,Sofa,Furniture,950,1,950,2024-02-13
33,Sophia Davis,Dallas,Bookshelf,Furniture,275,1,275,2024-02-14
34,James Wilson,Chicago,Bed Frame,Furniture,750,1,750,2024-02-15
35,Olivia Miller,Austin,Running Shoes,Sports,120,3,360,2024-02-16
36,William Moore,Seattle,Football,Sports,45,5,225,2024-02-17
37,Ava Taylor,Dallas,Tennis Racket,Sports,180,2,360,2024-02-18
38,Benjamin Anderson,Miami,Gym Bag,Sports,65,1,65,2024-02-19
39,Isabella Thomas,Houston,Yoga Mat,Sports,35,4,140,2024-02-20

In [45]:
# 44
orders.merge(customers, on='customer_id') \
      .groupby('customer_name')['total_amount'] \
      .sum() \
      .reset_index(name='total_spending') \
      .sort_values(by='total_spending', ascending=False) \
      .head(5)

    customer_name  total_spending
12  Olivia Miller            2960
4    Emma Johnson            2430
0      Ava Taylor            2260
9   Lucas Jackson            1940
5    Henry Harris            1850

In [46]:
# 45
orders.merge(products, on='product_id') \
      .groupby('product_name')['quantity'] \
      .sum() \
      .reset_index(name='units_sold') \
      .sort_values(by='units_sold', ascending=False) \
      .head(5)

     product_name  units_sold
4        Football           9
19       Yoga Mat           7
6      Headphones           5
9    Office Chair           5
11  Running Shoes           5

In [47]:
# 46
orders.merge(customers, on='customer_id') \
      .groupby('city')['total_amount'] \
      .sum() \
      .reset_index(name='revenue') \
      .sort_values(by='revenue', ascending=False)

      city  revenue
0   Austin     7240
2   Dallas     5865
1  Chicago     3005
6  Seattle     2815
3  Houston     2460
5  Phoenix     1940
4    Miami     1465

In [48]:
# 47
orders.merge(products, on='product_id') \
      .groupby('category')['total_amount'] \
      .sum() \
      .reset_index(name='revenue') \
      .sort_values(by='revenue', ascending=False)

          category  revenue
2  Home Appliances     8580
0      Electronics     7800
1        Furniture     6425
3           Sports     1985

In [49]:
# 48
orders.merge(customers, on='customer_id')[['customer_name', 'total_amount']] \
      .sort_values(by='total_amount', ascending=False) \
      .head(1)

  customer_name  total_amount
1  Emma Johnson          1600

In [50]:
# 49
orders.merge(customers, on='customer_id') \
      .groupby('customer_name')['order_id'] \
      .count() \
      .reset_index(name='total_orders') \
      .query('total_orders > 1')

        customer_name  total_orders
0          Ava Taylor             3
1   Benjamin Anderson             3
2    Charlotte Martin             2
3     Daniel Thompson             2
4        Emma Johnson             3
5        Henry Harris             2
6     Isabella Thomas             3
7        James Wilson             3
8          John Smith             3
9       Lucas Jackson             2
10          Mia White             2
11      Michael Brown             3
12      Olivia Miller             3
13       Sophia Davis             3
14      William Moore             3

In [51]:
# 50
products[~products['product_id'].isin(orders['product_id'])]

Empty DataFrame
Columns: [product_id, product_name, category, price, stock]
Index: []

In [52]:
# 51
orders.merge(products, on='product_id') \
      .groupby('category')['total_amount'] \
      .sum() \
      .reset_index(name='total_sales') \
      .query('total_sales > 10000')

Empty DataFrame
Columns: [category, total_sales]
Index: []

In [53]:
# 52
orders.merge(customers, on='customer_id') \
      .groupby('city')['total_amount'] \
      .sum() \
      .reset_index(name='total_sales') \
      .query('total_sales > 20000')

Empty DataFrame
Columns: [city, total_sales]
Index: []

In [54]:
# 53
products['discount'] = products['price'] * 0.10
products

    product_id     product_name         category  price  stock  discount
0          101           Laptop      Electronics   1200     15     120.0
1          102       Smartphone      Electronics    800     25      80.0
2          103           Tablet      Electronics    500     18      50.0
3          104       Headphones      Electronics    150     40      15.0
4          105      Smart Watch      Electronics    250     22      25.0
5          106     Refrigerator  Home Appliances   1400     10     140.0
6          107        Microwave  Home Appliances    300     12      30.0
7          108  Washing Machine  Home Appliances    900      8      90.0
8          109  Air Conditioner  Home Appliances   1100      7     110.0
9          110   Vacuum Cleaner  Home Appliances    220     14      22.0
10         111     Office Chair        Furniture    180     30      18.0
11         112     Dining Table        Furniture    650      9      65.0
12         113             Sofa        Furniture    950      6      95.0
13         114        Bookshelf        Furniture    275     16      27.5
14         115        Bed Frame        Furniture    750      5      75.0
15         116    Running Shoes           Sports    120     35      12.0
16         117         Football           Sports     45     50       4.5
17         118    Tennis Racket           Sports    180     20      18.0
18         119          Gym Bag           Sports     65     28       6.5
19         120         Yoga Mat           Sports     35     45       3.5

In [55]:
# 54
orders['tax'] = orders['total_amount'] * 0.05
orders

,order_id,customer_id,product_id,quantity,total_amount,order_date,tax
0,1,1,101,1,1200,2024-01-05,60.00
1,2,2,102,2,1600,2024-01-06,80.00
2,3,3,103,1,500,2024-01-07,25.00
3,4,4,104,3,450,2024-01-08,22.50
4,5,5,105,2,500,2024-01-09,25.00
5,6,6,106,1,1400,2024-01-10,70.00
6,7,7,107,2,600,2024-01-11,30.00
7,8,8,108,1,900,2024-01-12,45.00
8,9,9,109,1,1100,2024-01-13,55.00
9,10,10,110,2,440,2024-01-14,22.00
10,11,11,111,3,540,2024-01-15,27.00
11,12,12,112,1,650,2024-01-16,32.50
12,13,13,113,1,950,2024-01-17,47.50
13,14,14,114,2,550,2024-01-18,27.50
14,15,15,115,1,750,2024-01-19,37.50
15,16,1,116,2,240,2024-01-20,12.00
16,17,2,117,4,180,2024-01-21,9.00
17,18,3,118,1,180,2024-01-22,9.00
18,19,4,119,2,130,2024-01-23,6.50
19,20,5,120,3,105,2024-01-24,5.25
20,21,6,101,1,1200,2024-02-01,60.00
21,22,7,102,1,800,2024-02-02,40.00
22,23,8,103,2,1000,2024-02-03,50.00
23,24,9,104,2,300,2024-02-04,15.00
24,25,10,105,1,250,2024-02-05,12.50
25,26,11,106,1,1400,2024-02-06,70.00
26,27,12,107,1,300,2024-02-07,15.00
27,28,13,108,1,900,2024-02-08,45.00
28,29,14,109,1,1100,2024-02-09,55.00
29,30,15,110,2,440,2024-02-10,22.00
30,31,1,111,2,360,2024-02-11,18.00
31,32,2,112,1,650,2024-02-12,32.50
32,33,3,113,1,950,2024-02-13,47.50
33,34,4,114,1,275,2024-02-14,13.75
34,35,5,115,1,750,2024-02-15,37.50
35,36,6,116,3,360,2024-02-16,18.00
36,37,7,117,5,225,2024-02-17,11.25
37,38,8,118,2,360,2024-02-18,18.00
38,39,9,119,1,65,2024-02-19,3.25
39,40,10,120,4,140,2024-02-20,7.00

In [56]:
# 55
orders['final_amount'] = orders['total_amount'] + orders['tax']
orders

,order_id,customer_id,product_id,quantity,total_amount,order_date,tax,final_amount
0,1,1,101,1,1200,2024-01-05,60.00,1260.00
1,2,2,102,2,1600,2024-01-06,80.00,1680.00
2,3,3,103,1,500,2024-01-07,25.00,525.00
3,4,4,104,3,450,2024-01-08,22.50,472.50
4,5,5,105,2,500,2024-01-09,25.00,525.00
5,6,6,106,1,1400,2024-01-10,70.00,1470.00
6,7,7,107,2,600,2024-01-11,30.00,630.00
7,8,8,108,1,900,2024-01-12,45.00,945.00
8,9,9,109,1,1100,2024-01-13,55.00,1155.00
9,10,10,110,2,440,2024-01-14,22.00,462.00
10,11,11,111,3,540,2024-01-15,27.00,567.00
11,12,12,112,1,650,2024-01-16,32.50,682.50
12,13,13,113,1,950,2024-01-17,47.50,997.50
13,14,14,114,2,550,2024-01-18,27.50,577.50
14,15,15,115,1,750,2024-01-19,37.50,787.50
15,16,1,116,2,240,2024-01-20,12.00,252.00
16,17,2,117,4,180,2024-01-21,9.00,189.00
17,18,3,118,1,180,2024-01-22,9.00,189.00
18,19,4,119,2,130,2024-01-23,6.50,136.50
19,20,5,120,3,105,2024-01-24,5.25,110.25
20,21,6,101,1,1200,2024-02-01,60.00,1260.00
21,22,7,102,1,800,2024-02-02,40.00,840.00
22,23,8,103,2,1000,2024-02-03,50.00,1050.00
23,24,9,104,2,300,2024-02-04,15.00,315.00
24,25,10,105,1,250,2024-02-05,12.50,262.50
25,26,11,106,1,1400,2024-02-06,70.00,1470.00
26,27,12,107,1,300,2024-02-07,15.00,315.00
27,28,13,108,1,900,2024-02-08,45.00,945.00
28,29,14,109,1,1100,2024-02-09,55.00,1155.00
29,30,15,110,2,440,2024-02-10,22.00,462.00
30,31,1,111,2,360,2024-02-11,18.00,378.00
31,32,2,112,1,650,2024-02-12,32.50,682.50
32,33,3,113,1,950,2024-02-13,47.50,997.50
33,34,4,114,1,275,2024-02-14,13.75,288.75
34,35,5,115,1,750,2024-02-15,37.50,787.50
35,36,6,116,3,360,2024-02-16,18.00,378.00
36,37,7,117,5,225,2024-02-17,11.25,236.25
37,38,8,118,2,360,2024-02-18,18.00,378.00
38,39,9,119,1,65,2024-02-19,3.25,68.25
39,40,10,120,4,140,2024-02-20,7.00,147.00

In [57]:
# 56
customers.rename(columns={'customer_name':'name'})

    customer_id               name     city  age
0             1         John Smith   Dallas   32
1             2       Emma Johnson   Austin   28
2             3      Michael Brown  Houston   41
3             4       Sophia Davis   Dallas   35
4             5       James Wilson  Chicago   29
5             6      Olivia Miller   Austin   38
6             7      William Moore  Seattle   45
7             8         Ava Taylor   Dallas   26
8             9  Benjamin Anderson    Miami   31
9            10    Isabella Thomas  Houston   27
10           11      Lucas Jackson  Phoenix   36
11           12          Mia White   Dallas   24
12           13       Henry Harris   Austin   42
13           14   Charlotte Martin  Chicago   33
14           15    Daniel Thompson  Seattle   39

In [58]:
# 57
customers['customer_name'] = customers['customer_name'].str.upper()
customers

    customer_id      customer_name     city  age
0             1         JOHN SMITH   Dallas   32
1             2       EMMA JOHNSON   Austin   28
2             3      MICHAEL BROWN  Houston   41
3             4       SOPHIA DAVIS   Dallas   35
4             5       JAMES WILSON  Chicago   29
5             6      OLIVIA MILLER   Austin   38
6             7      WILLIAM MOORE  Seattle   45
7             8         AVA TAYLOR   Dallas   26
8             9  BENJAMIN ANDERSON    Miami   31
9            10    ISABELLA THOMAS  Houston   27
10           11      LUCAS JACKSON  Phoenix   36
11           12          MIA WHITE   Dallas   24
12           13       HENRY HARRIS   Austin   42
13           14   CHARLOTTE MARTIN  Chicago   33
14           15    DANIEL THOMPSON  Seattle   39

In [59]:
# 58
customers['customer_name'] = customers['customer_name'].str.lower()
customers

    customer_id      customer_name     city  age
0             1         john smith   Dallas   32
1             2       emma johnson   Austin   28
2             3      michael brown  Houston   41
3             4       sophia davis   Dallas   35
4             5       james wilson  Chicago   29
5             6      olivia miller   Austin   38
6             7      william moore  Seattle   45
7             8         ava taylor   Dallas   26
8             9  benjamin anderson    Miami   31
9            10    isabella thomas  Houston   27
10           11      lucas jackson  Phoenix   36
11           12          mia white   Dallas   24
12           13       henry harris   Austin   42
13           14   charlotte martin  Chicago   33
14           15    daniel thompson  Seattle   39

In [60]:
# 59
customers['city'] = customers['city'].fillna('Unknown')
customers

    customer_id      customer_name     city  age
0             1         john smith   Dallas   32
1             2       emma johnson   Austin   28
2             3      michael brown  Houston   41
3             4       sophia davis   Dallas   35
4             5       james wilson  Chicago   29
5             6      olivia miller   Austin   38
6             7      william moore  Seattle   45
7             8         ava taylor   Dallas   26
8             9  benjamin anderson    Miami   31
9            10    isabella thomas  Houston   27
10           11      lucas jackson  Phoenix   36
11           12          mia white   Dallas   24
12           13       henry harris   Austin   42
13           14   charlotte martin  Chicago   33
14           15    daniel thompson  Seattle   39

In [61]:
# 60
customers.drop_duplicates()

    customer_id      customer_name     city  age
0             1         john smith   Dallas   32
1             2       emma johnson   Austin   28
2             3      michael brown  Houston   41
3             4       sophia davis   Dallas   35
4             5       james wilson  Chicago   29
5             6      olivia miller   Austin   38
6             7      william moore  Seattle   45
7             8         ava taylor   Dallas   26
8             9  benjamin anderson    Miami   31
9            10    isabella thomas  Houston   27
10           11      lucas jackson  Phoenix   36
11           12          mia white   Dallas   24
12           13       henry harris   Austin   42
13           14   charlotte martin  Chicago   33
14           15    daniel thompson  Seattle   39

In [62]:
# 61
orders.sample(5)

,order_id,customer_id,product_id,quantity,total_amount,order_date,tax,final_amount
37,38,8,118,2,360,2024-02-18,18.00,378.00
6,7,7,107,2,600,2024-01-11,30.00,630.00
5,6,6,106,1,1400,2024-01-10,70.00,1470.00
2,3,3,103,1,500,2024-01-07,25.00,525.00
33,34,4,114,1,275,2024-02-14,13.75,288.75

In [63]:
# 62
sales_report = orders.merge(customers, on='customer_id') \
                     .merge(products, on='product_id')

sales_report.to_csv('final_sales_report.csv', index=False)

In [64]:
#new dataset
sales_dataset = orders.merge(customers, on='customer_id') \
                      .merge(products, on='product_id')

sales_dataset

,order_id,customer_id,product_id,quantity,total_amount,order_date,tax,final_amount,customer_name,city,age,product_name,category,price,stock,discount
0,1,1,101,1,1200,2024-01-05,60.00,1260.00,john smith,Dallas,32,Laptop,Electronics,1200,15,120.0
1,2,2,102,2,1600,2024-01-06,80.00,1680.00,emma johnson,Austin,28,Smartphone,Electronics,800,25,80.0
2,3,3,103,1,500,2024-01-07,25.00,525.00,michael brown,Houston,41,Tablet,Electronics,500,18,50.0
3,4,4,104,3,450,2024-01-08,22.50,472.50,sophia davis,Dallas,35,Headphones,Electronics,150,40,15.0
4,5,5,105,2,500,2024-01-09,25.00,525.00,james wilson,Chicago,29,Smart Watch,Electronics,250,22,25.0
5,6,6,106,1,1400,2024-01-10,70.00,1470.00,olivia miller,Austin,38,Refrigerator,Home Appliances,1400,10,140.0
6,7,7,107,2,600,2024-01-11,30.00,630.00,william moore,Seattle,45,Microwave,Home Appliances,300,12,30.0
7,8,8,108,1,900,2024-01-12,45.00,945.00,ava taylor,Dallas,26,Washing Machine,Home Appliances,900,8,90.0
8,9,9,109,1,1100,2024-01-13,55.00,1155.00,benjamin anderson,Miami,31,Air Conditioner,Home Appliances,1100,7,110.0
9,10,10,110,2,440,2024-01-14,22.00,462.00,isabella thomas,Houston,27,Vacuum Cleaner,Home Appliances,220,14,22.0
10,11,11,111,3,540,2024-01-15,27.00,567.00,lucas jackson,Phoenix,36,Office Chair,Furniture,180,30,18.0
11,12,12,112,1,650,2024-01-16,32.50,682.50,mia white,Dallas,24,Dining Table,Furniture,650,9,65.0
12,13,13,113,1,950,2024-01-17,47.50,997.50,henry harris,Austin,42,Sofa,Furniture,950,6,95.0
13,14,14,114,2,550,2024-01-18,27.50,577.50,charlotte martin,Chicago,33,Bookshelf,Furniture,275,16,27.5
14,15,15,115,1,750,2024-01-19,37.50,787.50,daniel thompson,Seattle,39,Bed Frame,Furniture,750,5,75.0
15,16,1,116,2,240,2024-01-20,12.00,252.00,john smith,Dallas,32,Running Shoes,Sports,120,35,12.0
16,17,2,117,4,180,2024-01-21,9.00,189.00,emma johnson,Austin,28,Football,Sports,45,50,4.5
17,18,3,118,1,180,2024-01-22,9.00,189.00,michael brown,Houston,41,Tennis Racket,Sports,180,20,18.0
18,19,4,119,2,130,2024-01-23,6.50,136.50,sophia davis,Dallas,35,Gym Bag,Sports,65,28,6.5
19,20,5,120,3,105,2024-01-24,5.25,110.25,james wilson,Chicago,29,Yoga Mat,Sports,35,45,3.5
20,21,6,101,1,1200,2024-02-01,60.00,1260.00,olivia miller,Austin,38,Laptop,Electronics,1200,15,120.0
21,22,7,102,1,800,2024-02-02,40.00,840.00,william moore,Seattle,45,Smartphone,Electronics,800,25,80.0
22,23,8,103,2,1000,2024-02-03,50.00,1050.00,ava taylor,Dallas,26,Tablet,Electronics,500,18,50.0
23,24,9,104,2,300,2024-02-04,15.00,315.00,benjamin anderson,Miami,31,Headphones,Electronics,150,40,15.0
24,25,10,105,1,250,2024-02-05,12.50,262.50,isabella thomas,Houston,27,Smart Watch,Electronics,250,22,25.0
25,26,11,106,1,1400,2024-02-06,70.00,1470.00,lucas jackson,Phoenix,36,Refrigerator,Home Appliances,1400,10,140.0
26,27,12,107,1,300,2024-02-07,15.00,315.00,mia white,Dallas,24,Microwave,Home Appliances,300,12,30.0
27,28,13,108,1,900,2024-02-08,45.00,945.00,henry harris,Austin,42,Washing Machine,Home Appliances,900,8,90.0
28,29,14,109,1,1100,2024-02-09,55.00,1155.00,charlotte martin,Chicago,33,Air Conditioner,Home Appliances,1100,7,110.0
29,30,15,110,2,440,2024-02-10,22.00,462.00,daniel thompson,Seattle,39,Vacuum Cleaner,Home Appliances,220,14,22.0
30,31,1,111,2,360,2024-02-11,18.00,378.00,john smith,Dallas,32,Office Chair,Furniture,180,30,18.0
31,32,2,112,1,650,2024-02-12,32.50,682.50,emma johnson,Austin,28,Dining Table,Furniture,650,9,65.0
32,33,3,113,1,950,2024-02-13,47.50,997.50,michael brown,Houston,41,Sofa,Furniture,950,6,95.0
33,34,4,114,1,275,2024-02-14,13.75,288.75,sophia davis,Dallas,35,Bookshelf,Furniture,275,16,27.5
34,35,5,115,1,750,2024-02-15,37.50,787.50,james wilson,Chicago,29,Bed Frame,Furniture,750,5,75.0
35,36,6,116,3,360,2024-02-16,18.00,378.00,olivia miller,Austin,38,Running Shoes,Sports,120,35,12.0
36,37,7,117,5,225,2024-02-17,11.25,236.25,william moore,Seattle,45,Football,Sports,45,50,4.5
37,38,8,118,2,360,2024-02-18,18.00,378.00,ava taylor,Dallas,26,Tennis Racket,Sports,180,20,18.0
38,39,9,119,1,65,2024-02-19,3.25,68.25,benjamin anderson,Miami,31,Gym Bag,Sports,65,28,6.5
39,40,10,120,4,140,2024-02-20,7.00,147.00,isabella thomas,Houston,27,Yoga Mat,Sports,35,45,3.5

In [65]:
# 1
sales_dataset.groupby('customer_name')['total_amount'] \
             .sum() \
             .reset_index(name='total_spending') \
             .sort_values(by='total_spending', ascending=False) \
             .head(1)

    customer_name  total_spending
12  olivia miller            2960

In [66]:
# 2
sales_dataset.groupby('city')['total_amount'] \
             .sum() \
             .reset_index(name='total_revenue') \
             .sort_values(by='total_revenue', ascending=False) \
             .head(1)

     city  total_revenue
0  Austin           7240

In [67]:
# 3
sales_dataset.groupby('category')['total_amount'] \
             .sum() \
             .reset_index(name='total_sales') \
             .sort_values(by='total_sales', ascending=False) \
             .head(1)

          category  total_sales
2  Home Appliances         8580

In [68]:
# 4
sales_dataset.groupby('product_name')['quantity'] \
             .sum() \
             .reset_index(name='total_units_sold') \
             .sort_values(by='total_units_sold', ascending=False) \
             .head(1)

  product_name  total_units_sold
4     Football                 9

In [69]:
# 5
sales_dataset.groupby('product_name')['total_amount'] \
             .sum() \
             .reset_index(name='total_revenue') \
             .sort_values(by='total_revenue', ascending=False)

       product_name  total_revenue
10     Refrigerator           2800
7            Laptop           2400
13       Smartphone           2400
0   Air Conditioner           2200
14             Sofa           1900
18  Washing Machine           1800
1         Bed Frame           1500
15           Tablet           1500
3      Dining Table           1300
8         Microwave            900
9      Office Chair            900
17   Vacuum Cleaner            880
2         Bookshelf            825
6        Headphones            750
12      Smart Watch            750
11    Running Shoes            600
16    Tennis Racket            540
4          Football            405
19         Yoga Mat            245
5           Gym Bag            195

In [70]:
# 6
sales_dataset.groupby('customer_name')['order_id'] \
             .count() \
             .reset_index(name='total_orders') \
             .query('total_orders > 1')

        customer_name  total_orders
0          ava taylor             3
1   benjamin anderson             3
2    charlotte martin             2
3     daniel thompson             2
4        emma johnson             3
5        henry harris             2
6     isabella thomas             3
7        james wilson             3
8          john smith             3
9       lucas jackson             2
10          mia white             2
11      michael brown             3
12      olivia miller             3
13       sophia davis             3
14      william moore             3

In [71]:
# 7
sales_dataset['total_amount'].mean()

np.float64(619.75)

In [72]:
# 8
products[~products['product_id'].isin(sales_dataset['product_id'])]

Empty DataFrame
Columns: [product_id, product_name, category, price, stock, discount]
Index: []

In [73]:
# 9
sales_dataset.groupby('customer_name')['total_amount'] \
             .sum() \
             .reset_index(name='total_spending') \
             .sort_values(by='total_spending', ascending=False) \
             .head(10)

        customer_name  total_spending
12      olivia miller            2960
4        emma johnson            2430
0          ava taylor            2260
9       lucas jackson            1940
5        henry harris            1850
8          john smith            1800
2    charlotte martin            1650
11      michael brown            1630
14      william moore            1625
1   benjamin anderson            1465

In [74]:
# 10
sales_dataset.groupby('product_name')['total_amount'] \
             .sum() \
             .reset_index(name='total_revenue') \
             .sort_values(by='total_revenue', ascending=False) \
             .head(10)

       product_name  total_revenue
10     Refrigerator           2800
7            Laptop           2400
13       Smartphone           2400
0   Air Conditioner           2200
14             Sofa           1900
18  Washing Machine           1800
1         Bed Frame           1500
15           Tablet           1500
3      Dining Table           1300
8         Microwave            900

In [75]:
# 11
sales_dataset.groupby('city')['total_amount'] \
             .sum() \
             .reset_index(name='total_revenue') \
             .sort_values(by='total_revenue', ascending=False)

      city  total_revenue
0   Austin           7240
2   Dallas           5865
1  Chicago           3005
6  Seattle           2815
3  Houston           2460
5  Phoenix           1940
4    Miami           1465

In [76]:
# 12
sales_dataset.groupby('category')['total_amount'] \
             .sum() \
             .reset_index(name='total_revenue') \
             .sort_values(by='total_revenue', ascending=False)

          category  total_revenue
2  Home Appliances           8580
0      Electronics           7800
1        Furniture           6425
3           Sports           1985